#!/usr/bin/env python
"""
RMS Discord Deployment Script (Go Backend)

Builds Go binary + frontend, packages into tar.gz, uploads to server via
POST /api/system/update?token=<deploy_token>.

Usage:
    python deploy.py --release   # Release deploy, creates tag, triggers CI/CD
    python deploy.py --hot-fix   # Hot-fix deploy, creates tag, triggers CI/CD
    python deploy.py --debug     # Debug deploy (no tag, no CI/CD)
    python deploy.py --dry-run --debug  # Build without uploading
"""

from __future__ import annotations

import argparse
import io
import os
import re
import subprocess
import sys
import tarfile
import time
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError
import json

PROJECT_ROOT = Path(__file__).parent.resolve()

SERVER_URL = os.environ.get("DEPLOY_SERVER", "https://preview-chatroom.rms.net.cn")
DEPLOY_TOKEN = os.environ.get("DEPLOY_TOKEN")

VERSION_FILE = PROJECT_ROOT / "current.version"
WEB_VERSION_FILE = PROJECT_ROOT / "packages" / "web" / "src" / "version.ts"
ELECTRON_VERSION_FILE = (
    PROJECT_ROOT / "packages" / "electron-renderer" / "src" / "version.ts"
)

WEB_DIR = PROJECT_ROOT / "packages" / "web"
WEB_DIST_DIR = WEB_DIR / "dist"
GO_DIR = PROJECT_ROOT / "backend-go"
GO_BINARY_NAME = "rms-discord-server"


def read_version_file() -> tuple[str, str]:
    if not VERSION_FILE.exists():
        print(f"Error: Version file not found: {VERSION_FILE}")
        sys.exit(1)
    content = VERSION_FILE.read_text()
    version_name = version_code = None
    for line in content.strip().splitlines():
        line = line.strip()
        if line.startswith("version="):
            version_name = line.split("=", 1)[1].strip()
        elif line.startswith("code="):
            version_code = line.split("=", 1)[1].strip()
    if not version_name or not version_code:
        print("Error: invalid current.version format")
        sys.exit(1)
    return version_name, version_code


def generate_version_files(version_name: str, version_code: str, commit_hash: str) -> None:
    content = f'''// Auto-generated by deploy.py - DO NOT EDIT
export const VERSION_NAME = "{version_name}"
export const VERSION_CODE = "{version_code}"
export const COMMIT_HASH = "{commit_hash}"
'''
    for f in (WEB_VERSION_FILE, ELECTRON_VERSION_FILE):
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)


def cleanup_version_files() -> None:
    default = '''// Auto-generated by deploy.py - DO NOT EDIT
export const VERSION_NAME = "0.0.0"
export const VERSION_CODE = "0"
export const COMMIT_HASH = "unknown"
'''
    for f in (WEB_VERSION_FILE, ELECTRON_VERSION_FILE):
        if f.exists():
            f.write_text(default)


def check_git_clean() -> tuple[bool, str]:
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"], cwd=PROJECT_ROOT,
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            return False, "Failed to run git status"
        lines = [l for l in result.stdout.strip().splitlines()
                 if not (l.endswith("deploy.py") or "version.ts" in l)]
        if lines:
            return False, "Working directory not clean:\n" + "\n".join(lines)
        return True, ""
    except FileNotFoundError:
        return False, "git not found"


def get_commit_hash() -> str:
    try:
        r = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                           cwd=PROJECT_ROOT, capture_output=True, text=True)
        if r.returncode == 0:
            return r.stdout.strip()
    except FileNotFoundError:
        pass
    return "unknown"


def get_last_release_version() -> str | None:
    try:
        r = subprocess.run(["git", "tag", "-l", "v*"], cwd=PROJECT_ROOT,
                           capture_output=True, text=True)
        if r.returncode != 0:
            return None
        versions = []
        for tag in r.stdout.strip().splitlines():
            m = re.match(r"^v(\d+\.\d+\.\d+)\(\d+\)$", tag)
            if m:
                versions.append(m.group(1))
        if not versions:
            return None
        versions.sort(key=lambda v: tuple(int(x) for x in v.split(".")), reverse=True)
        return versions[0]
    except Exception:
        return None


def create_git_tag(version: str, code: str) -> tuple[bool, str]:
    tag_name = f"v{version}({code})"
    try:
        r = subprocess.run(["git", "tag", tag_name], cwd=PROJECT_ROOT,
                           capture_output=True, text=True)
        if r.returncode != 0:
            return False, f"Failed to create tag: {r.stderr.strip()}"
        return True, tag_name
    except Exception as e:
        return False, f"Failed to create tag: {e}"


def git_push(with_tags: bool = False) -> tuple[bool, str]:
    try:
        r = subprocess.run(["git", "push"], cwd=PROJECT_ROOT,
                           capture_output=True, text=True)
        if r.returncode != 0:
            return False, f"Failed to push: {r.stderr.strip()}"
        if with_tags:
            r = subprocess.run(["git", "push", "--tags"], cwd=PROJECT_ROOT,
                               capture_output=True, text=True)
            if r.returncode != 0:
                return False, f"Failed to push tags: {r.stderr.strip()}"
        return True, ""
    except Exception as e:
        return False, f"Failed to push: {e}"


def build_frontend() -> tuple[bool, str]:
    try:
        r = subprocess.run(["pnpm", "run", "build:web"], cwd=PROJECT_ROOT,
                           capture_output=True, text=True, timeout=300)
        if r.returncode != 0:
            return False, f"Web build failed:\n{r.stderr[-2000:]}"
        if not WEB_DIST_DIR.exists():
            return False, "dist not found after build"
        return True, ""
    except subprocess.TimeoutExpired:
        return False, "Web build timed out"
    except FileNotFoundError:
        return False, "pnpm not found"


def build_go_binary() -> tuple[bool, str]:
    binary_path = GO_DIR / GO_BINARY_NAME
    env = os.environ.copy()
    env.update({"GOOS": "linux", "GOARCH": "amd64", "CGO_ENABLED": "0"})
    try:
        r = subprocess.run(
            ["go", "build", "-o", str(binary_path), "./cmd/server/main.go"],
            cwd=GO_DIR, capture_output=True, text=True, env=env, timeout=300,
        )
        if r.returncode != 0:
            return False, f"Go build failed:\n{r.stderr[-2000:]}"
        if not binary_path.exists():
            return False, "binary not found after build"
        return True, format_size(binary_path.stat().st_size)
    except subprocess.TimeoutExpired:
        return False, "Go build timed out"
    except FileNotFoundError:
        return False, "go not found"


def create_archive() -> tuple[io.BytesIO, int, int]:
    """Create tar.gz with Go binary + frontend dist."""
    buf = io.BytesIO()
    count = 0
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        # Add Go binary
        binary_path = GO_DIR / GO_BINARY_NAME
        tar.add(binary_path, arcname=GO_BINARY_NAME)
        count += 1
        # Add frontend dist
        for root, dirs, files in os.walk(WEB_DIST_DIR):
            for f in files:
                fpath = Path(root) / f
                arcname = "packages/web/dist/" + str(fpath.relative_to(WEB_DIST_DIR))
                tar.add(fpath, arcname=arcname)
                count += 1
    buf.seek(0)
    size = len(buf.getvalue())
    buf.seek(0)
    return buf, count, size


def deploy_upload(server_url: str, token: str, archive: io.BytesIO, dry_run: bool = False) -> bool:
    if dry_run:
        print("      [DRY RUN] Archive created, not uploading.")
        return True

    url = f"{server_url}/api/system/update?token={token}"
    boundary = "----DeployBoundary"
    body = io.BytesIO()

    body.write(f"--{boundary}\r\n".encode())
    body.write(b'Content-Disposition: form-data; name="file"; filename="deploy.tar.gz"\r\n')
    body.write(b"Content-Type: application/gzip\r\n\r\n")
    body.write(archive.read())
    body.write(f"\r\n--{boundary}--\r\n".encode())

    data = body.getvalue()
    req = Request(url, data=data, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")

    try:
        with urlopen(req, timeout=300) as resp:
            result = json.loads(resp.read())
            print(f"      Files extracted: {result.get('extracted_files', 0)}")
            print(f"      Binary updated: {result.get('binary_updated', False)}")
            restart = result.get("restart", {})
            if restart.get("scheduled"):
                print(f"      Restart: {restart.get('method', 'unknown')}")
            return True
    except HTTPError as e:
        body = e.read().decode()
        print(f"      ERROR: HTTP {e.code}: {body}")
        return False
    except URLError as e:
        print(f"      ERROR: {e.reason}")
        return False


def format_size(size: int) -> str:
    s = float(size)
    for unit in ["B", "KB", "MB", "GB"]:
        if s < 1024:
            return f"{s:.1f}{unit}"
        s /= 1024
    return f"{s:.1f}TB"


def main():
    parser = argparse.ArgumentParser(description="Deploy RMS Discord to server")
    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument("--release", action="store_true", help="Release deploy, creates tag, triggers CI/CD")
    mode_group.add_argument("--hot-fix", action="store_true", help="Hot-fix deploy, creates tag, triggers CI/CD")
    mode_group.add_argument("--debug", action="store_true", help="Debug deploy (no tag, no CI/CD)")
    parser.add_argument("--server", default=SERVER_URL, help=f"Server URL (default: {SERVER_URL})")
    parser.add_argument("--token", default=DEPLOY_TOKEN, help="Deploy token (from DEPLOY_TOKEN env)")
    parser.add_argument("--dry-run", action="store_true", help="Build without uploading")
    args = parser.parse_args()

    mode = "release" if args.release else ("hot-fix" if args.hot_fix else "debug")
    create_tag = mode in ("release", "hot-fix")

    if not args.dry_run:
        ok, msg = check_git_clean()
        if not ok:
            print(f"Error: {msg}")
            sys.exit(1)

    if not args.token and not args.dry_run:
        print("Error: Deploy token required. Use --token or set DEPLOY_TOKEN env var")
        sys.exit(1)

    version_name, version_code = read_version_file()
    version_name = version_name.lstrip("v")
    commit_hash = get_commit_hash()

    total = 7 if create_tag else 6
    step = 0

    step += 1
    print(f"[{step}/{total}] Version: v{version_name}({version_code}) [{mode}]")
    if mode == "release":
        last = get_last_release_version()
        if last and last == version_name:
            print(f"      ERROR: v{version_name} already released. Use --hot-fix.")
            sys.exit(1)

    step += 1
    print(f"\n[{step}/{total}] Generating version files...")
    generate_version_files(version_name, version_code, commit_hash)

    try:
        step += 1
        print(f"\n[{step}/{total}] Building frontend...")
        ok, err = build_frontend()
        if not ok:
            print(f"      ERROR: {err}"); sys.exit(1)
        print("      Done")

        step += 1
        print(f"\n[{step}/{total}] Cross-compiling Go binary (linux/amd64)...")
        ok, result = build_go_binary()
        if not ok:
            print(f"      ERROR: {result}"); sys.exit(1)
        print(f"      Binary: {GO_BINARY_NAME} ({result})")

        if create_tag:
            step += 1
            print(f"\n[{step}/{total}] Creating git tag...")
            ok, result = create_git_tag(version_name, version_code)
            if not ok:
                print(f"      ERROR: {result}"); sys.exit(1)
            print(f"      Tag: {result}")

        step += 1
        print(f"\n[{step}/{total}] Pushing to remote...")
        if args.dry_run:
            print("      [DRY RUN] Skipped")
        else:
            br = subprocess.run(["git", "symbolic-ref", "-q", "HEAD"],
                                cwd=PROJECT_ROOT, capture_output=True)
            if br.returncode != 0:
                print("      Skipped (detached HEAD)")
            else:
                ok, err = git_push(with_tags=create_tag)
                if not ok:
                    print(f"      ERROR: {err}"); sys.exit(1)
                print("      Pushed" + (" with tags" if create_tag else ""))

        step += 1
        print(f"\n[{step}/{total}] Packing and uploading...")
        start = time.time()
        archive, file_count, size = create_archive()
        print(f"      {file_count} files, {format_size(size)}")

        ok = deploy_upload(args.server, args.token, archive, dry_run=args.dry_run)
        if not ok:
            sys.exit(1)
        if not args.dry_run:
            print(f"      Completed in {time.time() - start:.1f}s")

        print(f"\nDeploy completed successfully!")

    finally:
        cleanup_version_files()
        binary = GO_DIR / GO_BINARY_NAME
        if binary.exists():
            binary.unlink()

    sys.exit(0)


if __name__ == "__main__":
    main()
