// Auto-generated by GitHub Actions on release builds - DO NOT EDIT.
// The committed placeholder carries dev values (code 0, empty items);
// release builds overwrite this file with the AI-generated changelog
// history (newest first).

export interface ChangelogEntry { en: string; zh: string }

export interface ReleaseChangelog {
  version: string
  code: number
  tag?: string
  date: string
  improvements: ChangelogEntry[]
  fixes: ChangelogEntry[]
}

export const CHANGELOG_HISTORY: ReleaseChangelog[] = [
  {
    version: 'dev',
    code: 0,
    date: '',
    improvements: [],
    fixes: [],
  },
]

export const CHANGELOG: ReleaseChangelog = CHANGELOG_HISTORY[0]

/**
 * Flatten every release inside (fromCode, toCode] into one merged
 * view so a user who skipped versions sees all of their changes in
 * a single dialog. `history` is newest-first; entries render
 * oldest -> newest with duplicates (same English text) removed.
 * Returns the newest release unchanged when there is nothing to
 * merge (fresh installs, unknown fromCode).
 */
export function mergeChangelog(
  history: ReleaseChangelog[],
  fromCode: number | null,
  toCode: number,
): ReleaseChangelog {
  const newest = history[0]
  if (fromCode == null || !Number.isFinite(fromCode) || fromCode >= toCode) {
    return newest
  }
  const window = history.filter(c => c.code > fromCode && c.code <= toCode).reverse()
  if (window.length === 0) return newest
  const improvements: ChangelogEntry[] = []
  const fixes: ChangelogEntry[] = []
  const add = (list: ChangelogEntry[], entry: ChangelogEntry) => {
    if (!list.some(item => item.en === entry.en)) list.push(entry)
  }
  for (const release of window) {
    release.improvements.forEach(entry => add(improvements, entry))
    release.fixes.forEach(entry => add(fixes, entry))
  }
  return { ...newest, improvements, fixes }
}
